# Site settings
author: Valerie H. Moore
title: ValerieHMoore
header-img: img/blog-homepage3.png
email: periwinkle17@outlook.com
copyright_name: Valerie H. Moore
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ValerieHMoore

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
